# Utilisez une image Node.js pour construire votre application Svelte
FROM node:22.0.0 as build


WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

ENV MODE="production"

COPY . .
RUN npm run build

# Étape de production
FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]