version: "3.3"

services:
  frontend:
    build:
      dockerfile: docker/dev/frontend.Dockerfile
      context: ../..
    image: erebe-frontend
    container_name: frontend
    hostname: frontend
    tty: true
    ports:
      - 127.0.0.1:8001:8001
    volumes:
      - ../../frontend/erebe/:/app:rw
    command: bash -c "npm install && npm run dev -- --host"


  backend:
    build:
      dockerfile: docker/dev/backend.Dockerfile
      context: ../..
    image: erebe-backend
    container_name: backend
    hostname: backend
    tty: true
    ports:
      - 127.0.0.1:8002:8002
    volumes:
      - ../../backend:/app:rw
      - ./data/suricata-config/:/app/suricata-config/
    command: >
      bash -c "poetry install && poetry run uvicorn main:app --reload --port 8002 --host 0.0.0.0"
    

networks:
  dev_internal:
    driver: bridge